### PR TITLE
added 0.8 to package.json

### PR DESCRIPTION
**Pull request by tbergeron**

### CODE REVIEW

**Comment by tbergeron** [comment]
Finally removed the whole engine tree, that way I think it does run for any version.

**Comment by Raynos** [comment]
@tbergeron removing the engine property is the correct solution

**Comment by Raynos** [comment]
@tbergeron published 0.1.17 on  npm with support for 0.8

**Comment by tbergeron** [comment]
@Raynos great! glad it was what to do.

**Pull request merged**
